# Feature Scalling

### 1. Install Dependencies

In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings("ignore")

### 2. Load Dataset

In [12]:
df = pd.read_csv('../data/processed/TelcoCustomerChurnPredictionFeatureEncoded.csv')
df.head()

,tenure,MonthlyCharges,TotalCharges,Churn,ServiceAdoptionScore,AvgMonthlyChargesPerService,PaymentMethodRisk,isPayementReliable,gender_Female,gender_Male,...,OnlineBackup_No,OnlineBackup_No internet service,OnlineBackup_Yes,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,tenure_binns_Established,tenure_binns_Loyal,tenure_binns_New,Contract
0,1,29.85,29.85,No,2,14.9250,1.0,1,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,34,56.95,1889.50,No,4,14.2375,0.7,1,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,2,53.85,108.15,Yes,4,13.4625,0.7,1,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,45,42.30,1840.75,No,4,10.5750,0.3,1,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,2,70.70,151.65,Yes,2,35.3500,1.0,1,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [13]:
numerical_variables = [
                        'MonthlyCharges', 'TotalCharges', 'tenure', "ServiceAdoptionScore", "AvgMonthlyChargesPerService", 
                      ]

for col in numerical_variables:
    standard_scalar = StandardScaler()
    df[col] = standard_scalar.fit_transform(df[col].values.reshape(df[col].shape[0], 1))

df.head()

,tenure,MonthlyCharges,TotalCharges,Churn,ServiceAdoptionScore,AvgMonthlyChargesPerService,PaymentMethodRisk,isPayementReliable,gender_Female,gender_Male,...,OnlineBackup_No,OnlineBackup_No internet service,OnlineBackup_Yes,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,tenure_binns_Established,tenure_binns_Loyal,tenure_binns_New,Contract
0,-1.277445,-1.160323,-0.994194,No,-0.821114,-0.722515,1.0,1,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.066327,-0.259629,-0.173740,No,0.131229,-0.834376,0.7,1,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,-1.236724,-0.362660,-0.959649,Yes,0.131229,-0.960474,0.7,1,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.514251,-0.746535,-0.195248,No,0.131229,-1.430290,0.3,1,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,-1.236724,0.197365,-0.940457,Yes,-0.821114,2.600771,1.0,1,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [14]:
df.to_csv('../data/processed/TelcoCustomerChurnPredictionFeatureScaled.csv', index=False)